# Generated by Django 3.2.5 on 2022-09-24 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movie',
            table='Movie',
        ),
    ]
